Data set: NYC taxi timings + NYC weather report

In [9]:
import pandas as pd
import numpy as np
import IPython.display as display

raw_df=pd.read_csv('../taxi_trips/refined_data.csv')
raw_df

,Unnamed: 0,year,month,date,hour,id,vendor_id,pickup_datetime,dropoff_datetime,passenger_count,...,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,avg_temp,snow_depth,snow_fall,precipitate,distance
0,0,2016,3,2016-03-14,17,id2875421,2,2016-03-14 17:24:55,2016-03-14 17:32:30,1,...,40.767937,-73.964630,40.765602,N,455,45.5,0.0,0.0,0.29,17.679539
1,1,2016,6,2016-06-12,0,id2377394,1,2016-06-12 00:43:35,2016-06-12 00:54:38,1,...,40.738564,-73.999481,40.731152,N,663,72.5,0.0,0.0,0.0,20.455904
2,2,2016,4,2016-04-06,19,id3504673,2,2016-04-06 19:32:31,2016-04-06 19:39:40,1,...,40.719971,-74.012268,40.706718,N,429,39.0,0.0,0.0,0.0,13.438206
3,3,2016,3,2016-03-26,13,id2181028,2,2016-03-26 13:30:55,2016-03-26 13:38:10,1,...,40.793209,-73.972923,40.782520,N,435,46.5,0.0,0.0,0.0,10.689569
4,4,2016,1,2016-01-30,22,id0801584,2,2016-01-30 22:01:40,2016-01-30 22:09:03,6,...,40.742195,-73.992081,40.749184,N,443,33.5,6.0,0.0,0.0,11.572403
5,5,2016,6,2016-06-17,22,id1813257,1,2016-06-17 22:34:59,2016-06-17 22:40:40,4,...,40.757839,-73.957405,40.765896,N,341,70.5,0.0,0.0,0.0,14.133173
6,6,2016,5,2016-05-21,7,id1324603,2,2016-05-21 07:54:58,2016-05-21 08:20:49,1,...,40.797779,-73.922470,40.760559,N,1551,60.0,0.0,0.0,0.04,59.801016
7,7,2016,5,2016-05-27,23,id1301050,1,2016-05-27 23:12:23,2016-05-27 23:16:38,1,...,40.738400,-73.985786,40.732815,N,255,80.0,0.0,0.0,0.0,14.789713
8,8,2016,3,2016-03-10,21,id0012891,2,2016-03-10 21:45:01,2016-03-10 22:05:26,1,...,40.744339,-73.973000,40.789989,N,1225,71.0,0.0,0.0,0.0,46.354645
9,9,2016,5,2016-05-10,22,id1436371,2,2016-05-10 22:08:41,2016-05-10 22:29:55,1,...,40.763840,-74.002228,40.732990,N,1274,56.5,0.0,0.0,0.0,36.536953
10,10,2016,5,2016-05-15,11,id1299289,2,2016-05-15 11:16:11,2016-05-15 11:34:59,4,...,40.749439,-73.956543,40.770630,N,1128,52.5,0.0,0.0,0.0,40.905155
11,11,2016,2,2016-02-19,9,id1187965,2,2016-02-19 09:52:46,2016-02-19 10:11:20,2,...,40.756680,-73.984406,40.760719,N,1114,31.5,0.0,0.0,0.0,21.800899
12,12,2016,6,2016-06-01,20,id0799785,2,2016-06-01 20:58:29,2016-06-01 21:02:49,1,...,40.767941,-73.966110,40.763000,N,260,74.5,0.0,0.0,0.0,10.978063
13,13,2016,5,2016-05-27,0,id2900608,2,2016-05-27 00:43:36,2016-05-27 01:07:10,1,...,40.727226,-73.974655,40.783070,N,1414,80.0,0.0,0.0,0.0,58.533161
14,14,2016,5,2016-05-16,15,id3319787,1,2016-05-16 15:29:02,2016-05-16 15:32:33,1,...,40.768593,-73.948761,40.771545,N,211,54.5,0.0,0.0,0.0,7.369355
15,15,2016,4,2016-04-14,8,id1154431,1,2016-04-14 08:48:26,2016-04-14 09:00:37,1,...,40.745804,-73.999657,40.723343,N,731,52.5,0.0,0.0,0.0,23.101323
16,16,2016,6,2016-06-27,9,id3552682,1,2016-06-27 09:55:13,2016-06-27 10:17:10,1,...,40.713013,-73.979195,40.749924,N,1317,75.0,0.0,0.0,0.45,44.461926
17,17,2016,6,2016-06-05,13,id3390316,2,2016-06-05 13:47:23,2016-06-05 13:51:34,1,...,40.738197,-73.991203,40.727871,N,251,68.0,0.0,0.0,0.91,12.655699
18,18,2016,2,2016-02-28,2,id2070428,1,2016-02-28 02:23:02,2016-02-28 02:31:08,1,...,40.742420,-73.962852,40.760635,N,486,49.0,0.0,0.0,0.0,25.271351
19,19,2016,4,2016-04-01,12,id0809232,2,2016-04-01 12:12:25,2016-04-01 12:23:17,1,...,40.753361,-73.963997,40.763458,N,652,70.0,0.0,0.0,0.02,18.533339
20,20,2016,4,2016-04-09,3,id2352683,1,2016-04-09 03:34:27,2016-04-09 03:41:30,1,...,40.758812,-73.993324,40.740322,N,423,39.5,0.0,T,0.11,18.663566
21,21,2016,6,2016-06-25,10,id1603037,1,2016-06-25 10:36:26,2016-06-25 10:55:49,1,...,40.747173,-74.006142,40.704384,N,1163,75.0,0.0,0.0,0.0,44.602782
22,22,2016,2,2016-02-14,13,id0129640,2,2016-02-14 13:27:56,2016-02-14 13:49:19,1,...,40.771358,-73.974968,40.732792,N,1283,7.0,0.0,0.0,0.0,42.725376
23,23,2016,2,2016-02-27,21,id3587298,1,2016-02-27 21:56:01,2016-02-27 22:14:51,1,...,40.749874,-73.958832,40.800961,N,1130,33.5,0.0,0.0,0.0,56.846024
24,24,2016,6,2016-06-20,23,id2104175,1,2016-06-20 23:07:16,2016-06-20 23:18:50,1,...,40.713192,-73.949539,40.680252,N,694,74.0,0.0,0.0,0.0,34.119999
25,25,2016,6,2016-06-13,21,id3973319,2,2016-06-13 21:57:27,2016-06-13 22:12:19,1,...,40.713306,-73.982849,40.692299,N,892,65.5,0.0,0.0,0.0,23.886052
26,26,2016,5,2016-05-17,10,id0266980,1,2016-05-17 10:47:51,2016-05-17 11:12:30,1,...,40.761669,-73.996239,40.725368,N,1479,58.0,0.0,0.0,0.0,44.246818
27,27,2016,5,2016-05-21,13,id2822549,2,2016-05-21 13:03:24,2016-05-21 13:20:52,1,...,40.720039,-74.010361,40.672138,N,1048,60.0,0.0,0.0,0.04,49.403960
28,28,2016,5,2016-05-10,19,id3075902,2,2016-05-10 19:27:38,2016-05-10 19:44:40,2,...,40.706589,-73.985817,40.744202,N,1022,56.5,0.0,0.0,0.0,42.452148
29,29,2016,1,2016-01-09,12,id3970352,1,2016-01-09 12:55:35,2016-01-09 13:07:22,1,...,40.712589,-73.998634,40.722809,N,707,43.5,0.0,0.0,T,14.552806
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915,915,2016,3,2016-03-24,18,id3105039,2,2016-03-24 18:30:07,2016-03-24 18:32:10,2,...,40.764900,-73.980339,40.767536,N,123,49.5,0,0.0,0.00,4.407514
916,916,2016,4,2016-04-08,0,id2299069,2,2016-04-08 00:26:47,2016-04-08 00:35:37,4,...,40.757763,-73.968132,40.757317,N,530,45.0,0,0.0,0.01,15.143297
917,917,2016,6,2016-06-25,11,id2470556,2,2016-06-25 11:01:21,2016-06-25 11:18:26,1,...,40.767193,-73.973190,40.746159,N,1025,75.0,0,0.0,0.00,24.779844
918,918,2016,6,2016-06-16,14,id3660750,2,2016-06-16 14:10:08,2016-06-16 14:15:12,1,...,40.755341,-73.971291,40.761028,N,304,69.5,0,0.0,0.22,7.113649
919,919,2016,2,2016-02-05,5,id0627179,2,2016-02-05 05:48:08,2016-02-05 05:56:46,6,...,40.739262,-73.981812,40.724590,N,518,37.5,1,2.5,0.53,24.239116
920,920,2016,3,2016-03-17,20,id2743455,2,2016-03-17 20:33:17,2016-03-17 20:40:44,2,...,40.784000,-73.944763,40.834408,N,447,54.0,0,0.0,T,61.543651
921,921,2016,4,2016-04-18,17,id3481094,1,2016-04-18 17:23:58,2016-04-18 17:27:22,1,...,40.758511,-73.980385,40.759766,N,204,66.5,0,0.0,0.00,7.920198
922,922,2016,2,2016-02-19,12,id1240888,1,2016-02-19 12:29:56,2016-02-19 12:40:48,1,...,40.759548,-73.987511,40.780308,N,652,31.5,0,0.0,0.00,21.672983
923,923,2016,3,2016-03-13,19,id1850357,2,2016-03-13 19:38:04,2016-03-13 19:52:20,1,...,40.721340,-73.999710,40.738564,N,856,56.0,0,0.0,T,17.234995
924,924,2016,5,2016-05-01,11,id1282615,2,2016-05-01 11:49:32,2016-05-01 11:54:59,2,...,40.739300,-74.006508,40.721531,N,327,48.0,0,0.0,0.16,19.277837
925,925,2016,1,2016-01-18,15,id3600299,1,2016-01-18 15:52:47,2016-01-18 16:01:42,3,...,40.779243,-73.978760,40.759171,N,535,24.5,T,T,T,20.105101
926,926,2016,4,2016-04-24,0,id0671052,1,2016-04-24 00:19:46,2016-04-24 00:25:32,2,...,40.729889,-73.984123,40.725410,N,346,57.5,0,0.0,0.00,5.606089
927,927,2016,1,2016-01-04,21,id0702699,2,2016-01-04 21:09:10,2016-01-04 21:19:26,1,...,40.783058,-73.952652,40.799919,N,616,25.0,0,0.0,0.00,30.829541
928,928,2016,4,2016-04-08,7,id0862403,2,2016-04-08 07:05:14,2016-04-08 07:19:43,1,...,40.777493,-73.939621,40.805264,N,869,45.0,0,0.0,0.01,51.001831
929,929,2016,1,2016-01-12,9,id1442956,2,2016-01-12 09:07:30,2016-01-12 09:30:52,5,...,40.745731,-73.963638,40.758690,N,1402,34.5,0,T,0.00,43.785830
930,930,2016,6,2016-06-16,8,id1774111,1,2016-06-16 08:38:03,2016-06-16 08:45:24,1,...,40.774811,-73.996124,40.761631,N,441,69.5,0,0.0,0.22,15.340770
931,931,2016,4,2016-04-11,10,id1333989,1,2016-04-11 10:59:10,2016-04-11 11:05:30,1,...,40.744431,-73.978325,40.737736,N,380,54.0,0,0.0,0.01,8.583060
932,932,2016,5,2016-05-25,13,id3812910,2,2016-05-25 13:50:26,2016-05-25 13:59:58,1,...,40.736511,-74.012711,40.702179,N,572,74.5,0,0.0,0.00,46.061976
933,933,2016,5,2016-05-20,10,id3740726,1,2016-05-20 10:53:52,2016-05-20 11:15:35,2,...,40.717121,-73.955788,40.764362,N,1303,64.5,0,0.0,0.00,74.001989
934,934,2016,1,2016-01-26,2,id3030554,1,2016-01-26 02:01:09,2016-01-26 02:24:31,1,...,40.746021,-73.923714,40.767948,N,1402,43.0,17,0.0,0.00,68.044673
935,935,2016,3,2016-03-17,11,id2891699,2,2016-03-17 11:51:09,2016-03-17 12:09:37,5,...,40.761639,-74.011993,40.718929,N,1108,54.0,0,0.0,T,46.264063
936,936,2016,2,2016-02-24,16,id3498529,1,2016-02-24 16:25:29,2016-02-24 16:30:04,1,...,40.787930,-73.977478,40.782871,N,275,48.0,0,0.0,1.22,5.490880
937,937,2016,2,2016-02-13,21,id0244668,1,2016-02-13 21:41:23,2016-02-13 21:53:40,4,...,40.733498,-74.007256,40.733879,N,737,14.0,0,0.0,0.00,14.233933
938,938,2016,3,2016-03-29,14,id1963642,1,2016-03-29 14:46:36,2016-03-29 15:06:37,1,...,40.760746,-73.952446,40.772186,N,1201,46.5,0,0.0,0.00,31.849699
939,939,2016,4,2016-04-26,8,id1913200,1,2016-04-26 08:25:01,2016-04-26 08:52:06,1,...,40.714916,-73.988525,40.754757,N,1625,53.5,0,0.0,0.24,48.455671
940,940,2016,2,2016-02-09,20,id3877674,1,2016-02-09 20:42:41,2016-02-09 21:06:45,1,...,40.712364,-73.836533,40.719028,N,1444,31.5,T,T,0.00,173.384043
941,941,2016,5,2016-05-09,20,id3892641,1,2016-05-09 20:18:42,2016-05-09 20:26:11,1,...,40.761276,-73.984802,40.748276,N,449,62.0,0,0.0,0.00,16.449543
942,942,2016,4,2016-04-02,0,id2287030,2,2016-04-02 00:00:33,2016-04-02 00:03:23,2,...,40.762932,-73.982552,40.777500,N,170,55.0,0,0.0,0.16,17.956759
943,943,2016,3,2016-03-21,12,id0838992,2,2016-03-21 12:58:05,2016-03-21 13:06:25,1,...,40.754944,-73.984398,40.744278,N,500,41.0,T,0.5,0.06,13.029891
944,944,2016,5,2016-05-08,10,id2551093,1,2016-05-08 10:59:20,2016-05-08 11:07:30,1,...,40.644470,-73.811302,40.670212,N,490,57.5,0,0.0,0.16,38.907557

In [16]:
#learning the data structure
raw_df.describe
#columns explanation:

<bound method NDFrame.describe of      Unnamed: 0  year  month        date  hour         id  vendor_id  \
0             0  2016      3  2016-03-14    17  id2875421          2
1             1  2016      6  2016-06-12     0  id2377394          1
2             2  2016      4  2016-04-06    19  id3504673          2
3             3  2016      3  2016-03-26    13  id2181028          2
4             4  2016      1  2016-01-30    22  id0801584          2
5             5  2016      6  2016-06-17    22  id1813257          1
6             6  2016      5  2016-05-21     7  id1324603          2
7             7  2016      5  2016-05-27    23  id1301050          1
8             8  2016      3  2016-03-10    21  id0012891          2
9             9  2016      5  2016-05-10    22  id1436371          2
10           10  2016      5  2016-05-15    11  id1299289          2
11           11  2016      2  2016-02-19     9  id1187965          2
12           12  2016      6  2016-06-01    20  id0799785          2
13           13  2016      5  2016-05-27     0  id2900608          2
14           14  2016      5  2016-05-16    15  id3319787          1
15           15  2016      4  2016-04-14     8  id1154431          1
16           16  2016      6  2016-06-27     9  id3552682          1
17           17  2016      6  2016-06-05    13  id3390316          2
18           18  2016      2  2016-02-28     2  id2070428          1
19           19  2016      4  2016-04-01    12  id0809232          2
20           20  2016      4  2016-04-09     3  id2352683          1
21           21  2016      6  2016-06-25    10  id1603037          1
22           22  2016      2  2016-02-14    13  id0129640          2
23           23  2016      2  2016-02-27    21  id3587298          1
24           24  2016      6  2016-06-20    23  id2104175          1
25           25  2016      6  2016-06-13    21  id3973319          2
26           26  2016      5  2016-05-17    10  id0266980          1
27           27  2016      5  2016-05-21    13  id2822549          2
28           28  2016      5  2016-05-10    19  id3075902          2
29           29  2016      1  2016-01-09    12  id3970352          1
..          ...   ...    ...         ...   ...        ...        ...
915         915  2016      3  2016-03-24    18  id3105039          2
916         916  2016      4  2016-04-08     0  id2299069          2
917         917  2016      6  2016-06-25    11  id2470556          2
918         918  2016      6  2016-06-16    14  id3660750          2
919         919  2016      2  2016-02-05     5  id0627179          2
920         920  2016      3  2016-03-17    20  id2743455          2
921         921  2016      4  2016-04-18    17  id3481094          1
922         922  2016      2  2016-02-19    12  id1240888          1
923         923  2016      3  2016-03-13    19  id1850357          2
924         924  2016      5  2016-05-01    11  id1282615          2
925         925  2016      1  2016-01-18    15  id3600299          1
926         926  2016      4  2016-04-24     0  id0671052          1
927         927  2016      1  2016-01-04    21  id0702699          2
928         928  2016      4  2016-04-08     7  id0862403          2
929         929  2016      1  2016-01-12     9  id1442956          2
930         930  2016      6  2016-06-16     8  id1774111          1
931         931  2016      4  2016-04-11    10  id1333989          1
932         932  2016      5  2016-05-25    13  id3812910          2
933         933  2016      5  2016-05-20    10  id3740726          1
934         934  2016      1  2016-01-26     2  id3030554          1
935         935  2016      3  2016-03-17    11  id2891699          2
936         936  2016      2  2016-02-24    16  id3498529          1
937         937  2016      2  2016-02-13    21  id0244668          1
938         938  2016      3  2016-03-29    14  id1963642          1
939         939  2016      4  2016-04-26     8  id1913200          1
940         940  2016      2  2016-02-09    20  id3877674          1
941         941  2016      5  2016-05-09    20  id3892641          1
942         942  2016      4  2016-04-02     0  id2287030          2
943         943  2016      3  2016-03-21    12  id0838992          2
944         944  2016      5  2016-05-08    10  id2551093          1

         pickup_datetime     dropoff_datetime  passenger_count     ...      \
0    2016-03-14 17:24:55  2016-03-14 17:32:30                1     ...
1    2016-06-12 00:43:35  2016-06-12 00:54:38                1     ...
2    2016-04-06 19:32:31  2016-04-06 19:39:40                1     ...
3    2016-03-26 13:30:55  2016-03-26 13:38:10                1     ...
4    2016-01-30 22:01:40  2016-01-30 22:09:03                6     ...
5    2016-06-17 22:34:59  2016-06-17 22:40:40                4     ...
6    2016-05-21 07:54:58  2016-05-21 08:20:49                1     ...
7    2016-05-27 23:12:23  2016-05-27 23:16:38                1     ...
8    2016-03-10 21:45:01  2016-03-10 22:05:26                1     ...
9    2016-05-10 22:08:41  2016-05-10 22:29:55                1     ...
10   2016-05-15 11:16:11  2016-05-15 11:34:59                4     ...
11   2016-02-19 09:52:46  2016-02-19 10:11:20                2     ...
12   2016-06-01 20:58:29  2016-06-01 21:02:49                1     ...
13   2016-05-27 00:43:36  2016-05-27 01:07:10                1     ...
14   2016-05-16 15:29:02  2016-05-16 15:32:33                1     ...
15   2016-04-14 08:48:26  2016-04-14 09:00:37                1     ...
16   2016-06-27 09:55:13  2016-06-27 10:17:10                1     ...
17   2016-06-05 13:47:23  2016-06-05 13:51:34                1     ...
18   2016-02-28 02:23:02  2016-02-28 02:31:08                1     ...
19   2016-04-01 12:12:25  2016-04-01 12:23:17                1     ...
20   2016-04-09 03:34:27  2016-04-09 03:41:30                1     ...
21   2016-06-25 10:36:26  2016-06-25 10:55:49                1     ...
22   2016-02-14 13:27:56  2016-02-14 13:49:19                1     ...
23   2016-02-27 21:56:01  2016-02-27 22:14:51                1     ...
24   2016-06-20 23:07:16  2016-06-20 23:18:50                1     ...
25   2016-06-13 21:57:27  2016-06-13 22:12:19                1     ...
26   2016-05-17 10:47:51  2016-05-17 11:12:30                1     ...
27   2016-05-21 13:03:24  2016-05-21 13:20:52                1     ...
28   2016-05-10 19:27:38  2016-05-10 19:44:40                2     ...
29   2016-01-09 12:55:35  2016-01-09 13:07:22                1     ...
..                   ...                  ...              ...     ...
915  2016-03-24 18:30:07  2016-03-24 18:32:10                2     ...
916  2016-04-08 00:26:47  2016-04-08 00:35:37                4     ...
917  2016-06-25 11:01:21  2016-06-25 11:18:26                1     ...
918  2016-06-16 14:10:08  2016-06-16 14:15:12                1     ...
919  2016-02-05 05:48:08  2016-02-05 05:56:46                6     ...
920  2016-03-17 20:33:17  2016-03-17 20:40:44                2     ...
921  2016-04-18 17:23:58  2016-04-18 17:27:22                1     ...
922  2016-02-19 12:29:56  2016-02-19 12:40:48                1     ...
923  2016-03-13 19:38:04  2016-03-13 19:52:20                1     ...
924  2016-05-01 11:49:32  2016-05-01 11:54:59                2     ...
925  2016-01-18 15:52:47  2016-01-18 16:01:42                3     ...
926  2016-04-24 00:19:46  2016-04-24 00:25:32                2     ...
927  2016-01-04 21:09:10  2016-01-04 21:19:26                1     ...
928  2016-04-08 07:05:14  2016-04-08 07:19:43                1     ...
929  2016-01-12 09:07:30  2016-01-12 09:30:52                5     ...
930  2016-06-16 08:38:03  2016-06-16 08:45:24                1     ...
931  2016-04-11 10:59:10  2016-04-11 11:05:30                1     ...
932  2016-05-25 13:50:26  2016-05-25 13:59:58                1     ...
933  2016-05-20 10:53:52  2016-05-20 11:15:35                2     ...
934  2016-01-26 02:01:09  2016-01-26 02:24:31                1     ...
935  2016-03-17 11:51:09  2016-03-17 12:09:37                5     ...
936  2016-02-24 16:25:29  2016-02-24 16:30:04                1     ...
937  2016-02-13 21:41:23  2016-02-13 21:53:40                4     ...
938  2016-03-29 14:46:36  2016-03-29 15:06:37                1     ...
939  2016-04-26 08:25:01  2016-04-26 08:52:06                1     ...
940  2016-02-09 20:42:41  2016-02-09 21:06:45                1     ...
941  2016-05-09 20:18:42  2016-05-09 20:26:11                1     ...
942  2016-04-02 00:00:33  2016-04-02 00:03:23                2     ...
943  2016-03-21 12:58:05  2016-03-21 13:06:25                1     ...
944  2016-05-08 10:59:20  2016-05-08 11:07:30                1     ...

     pickup_latitude  dropoff_longitude  dropoff_latitude  store_and_fwd_flag  \
0          40.767937         -73.964630         40.765602                   N
1          40.738564         -73.999481         40.731152                   N
2          40.719971         -74.012268         40.706718                   N
3          40.793209         -73.972923         40.782520                   N
4          40.742195         -73.992081         40.749184                   N
5          40.757839         -73.957405         40.765896                   N
6          40.797779         -73.922470         40.760559                   N
7          40.738400         -73.985786         40.732815                   N
8          40.744339         -73.973000         40.789989                   N
9          40.763840         -74.002228         40.732990                   N
10         40.749439         -73.956543         40.770630                   N
11         40.756680         -73.984406         40.760719                   N
12         40.767941         -73.966110         40.763000                   N
13         40.727226         -73.974655         40.783070                   N
14         40.768593         -73.948761         40.771545                   N
15         40.745804         -73.999657         40.723343                   N
16         40.713013         -73.979195         40.749924                   N
17         40.738197         -73.991203         40.727871                   N
18         40.742420         -73.962852         40.760635                   N
19         40.753361         -73.963997         40.763458                   N
20         40.758812         -73.993324         40.740322                   N
21         40.747173         -74.006142         40.704384                   N
22         40.771358         -73.974968         40.732792                   N
23         40.749874         -73.958832         40.800961                   N
24         40.713192         -73.949539         40.680252                   N
25         40.713306         -73.982849         40.692299                   N
26         40.761669         -73.996239         40.725368                   N
27         40.720039         -74.010361         40.672138                   N
28         40.706589         -73.985817         40.744202                   N
29         40.712589         -73.998634         40.722809                   N
..               ...                ...               ...                 ...
915        40.764900         -73.980339         40.767536                   N
916        40.757763         -73.968132         40.757317                   N
917        40.767193         -73.973190         40.746159                   N
918        40.755341         -73.971291         40.761028                   N
919        40.739262         -73.981812         40.724590                   N
920        40.784000         -73.944763         40.834408                   N
921        40.758511         -73.980385         40.759766                   N
922        40.759548         -73.987511         40.780308                   N
923        40.721340         -73.999710         40.738564                   N
924        40.739300         -74.006508         40.721531                   N
925        40.779243         -73.978760         40.759171                   N
926        40.729889         -73.984123         40.725410                   N
927        40.783058         -73.952652         40.799919                   N
928        40.777493         -73.939621         40.805264                   N
929        40.745731         -73.963638         40.758690                   N
930        40.774811         -73.996124         40.761631                   N
931        40.744431         -73.978325         40.737736                   N
932        40.736511         -74.012711         40.702179                   N
933        40.717121         -73.955788         40.764362                   N
934        40.746021         -73.923714         40.767948                   N
935        40.761639         -74.011993         40.718929                   N
936        40.787930         -73.977478         40.782871                   N
937        40.733498         -74.007256         40.733879                   N
938        40.760746         -73.952446         40.772186                   N
939        40.714916         -73.988525         40.754757                   N
940        40.712364         -73.836533         40.719028                   N
941        40.761276         -73.984802         40.748276                   N
942        40.762932         -73.982552         40.777500                   N
943        40.754944         -73.984398         40.744278                   N
944        40.644470         -73.811302         40.670212                   N

    trip_duration  avg_temp  snow_depth snow_fall precipitate    distance
0             455      45.5         0.0       0.0        0.29   17.679539
1             663      72.5         0.0       0.0         0.0   20.455904
2             429      39.0         0.0       0.0         0.0   13.438206
3             435      46.5         0.0       0.0         0.0   10.689569
4             443      33.5         6.0       0.0         0.0   11.572403
5             341      70.5         0.0       0.0         0.0   14.133173
6            1551      60.0         0.0       0.0        0.04   59.801016
7             255      80.0         0.0       0.0         0.0   14.789713
8            1225      71.0         0.0       0.0         0.0   46.354645
9            1274      56.5         0.0       0.0         0.0   36.536953
10           1128      52.5         0.0       0.0         0.0   40.905155
11           1114      31.5         0.0       0.0         0.0   21.800899
12            260      74.5         0.0       0.0         0.0   10.978063
13           1414      80.0         0.0       0.0         0.0   58.533161
14            211      54.5         0.0       0.0         0.0    7.369355
15            731      52.5         0.0       0.0         0.0   23.101323
16           1317      75.0         0.0       0.0        0.45   44.461926
17            251      68.0         0.0       0.0        0.91   12.655699
18            486      49.0         0.0       0.0         0.0   25.271351
19            652      70.0         0.0       0.0        0.02   18.533339
20            423      39.5         0.0         T        0.11   18.663566
21           1163      75.0         0.0       0.0         0.0   44.602782
22           1283       7.0         0.0       0.0         0.0   42.725376
23           1130      33.5         0.0       0.0         0.0   56.846024
24            694      74.0         0.0       0.0         0.0   34.119999
25            892      65.5         0.0       0.0         0.0   23.886052
26           1479      58.0         0.0       0.0         0.0   44.246818
27           1048      60.0         0.0       0.0        0.04   49.403960
28           1022      56.5         0.0       0.0         0.0   42.452148
29            707      43.5         0.0       0.0           T   14.552806
..            ...       ...         ...       ...         ...         ...
915           123      49.5           0       0.0        0.00    4.407514
916           530      45.0           0       0.0        0.01   15.143297
917          1025      75.0           0       0.0        0.00   24.779844
918           304      69.5           0       0.0        0.22    7.113649
919           518      37.5           1       2.5        0.53   24.239116
920           447      54.0           0       0.0           T   61.543651
921           204      66.5           0       0.0        0.00    7.920198
922           652      31.5           0       0.0        0.00   21.672983
923           856      56.0           0       0.0           T   17.234995
924           327      48.0           0       0.0        0.16   19.277837
925           535      24.5           T         T           T   20.105101
926           346      57.5           0       0.0        0.00    5.606089
927           616      25.0           0       0.0        0.00   30.829541
928           869      45.0           0       0.0        0.01   51.001831
929          1402      34.5           0         T        0.00   43.785830
930           441      69.5           0       0.0        0.22   15.340770
931           380      54.0           0       0.0        0.01    8.583060
932           572      74.5           0       0.0        0.00   46.061976
933          1303      64.5           0       0.0        0.00   74.001989
934          1402      43.0          17       0.0        0.00   68.044673
935          1108      54.0           0       0.0           T   46.264063
936           275      48.0           0       0.0        1.22    5.490880
937           737      14.0           0       0.0        0.00   14.233933
938          1201      46.5           0       0.0        0.00   31.849699
939          1625      53.5           0       0.0        0.24   48.455671
940          1444      31.5           T         T        0.00  173.384043
941           449      62.0           0       0.0        0.00   16.449543
942           170      55.0           0       0.0        0.16   17.956759
943           500      41.0           T       0.5        0.06   13.029891
944           490      57.5           0       0.0        0.16   38.907557

[945 rows x 21 columns]>

In [ ]:
#changing columns: year,month,hour,vendor_id, to categorical
#separate data in columns: pickup_datetime, dropoff_datetime, 
#change col trip_duration from seconds to minutes
#change col avg_temp from fahrenheit to celsius by this formula: (F-32)*(5/9)

In [ ]:
#looking fo missing values- "T"
if raw_df.precipitate